language: c
dist: trusty
services: docker

env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "FJ1/E5vVttd4+cFLQVdFt4rHNX28aGIvAWXduy6ZqQgZbfa0omsHcZXAq0t1qFz14ryTxEtxqY/aXw6OSG+t6a8OyrOi9jEdTIUpEDCyPvdZ299injPt1SiJRxzoDNo1CquwUE20y2pFOnTpVp6bIkH49o0oAxBijtb5fDj54KY="

matrix:
  include:
  - compiler: gcc
    env: TEST="basic" ASAN="--enable-asan" OPENCL="yes" BUILD_OPTS=""

  - compiler: clang
    env: TEST="basic" ASAN="" OPENCL="yes" BUILD_OPTS=""

  #Test a non OpenMP build
  - env: TEST="basic" ASAN="" OPENCL="yes" BUILD_OPTS="--disable-native-tests --disable-openmp"

  #Test JtR using a recent OS/compiler
  - env: TEST="fresh test"   ASAN="--enable-asan"

  - env: TEST="TS --restore" ASAN=""

  allow_failures:
  - env: TEST="basic" ASAN="" OPENCL="yes" BUILD_OPTS="--disable-native-tests --disable-openmp"

  - env: TEST="fresh test"   ASAN="--enable-asan"

  - env: TEST="TS --restore" ASAN=""

  fast_finish: true

before_install:
  - export OMP_NUM_THREADS=4

script:
  - .travis/check.sh

addons:
  coverity_scan:
    project:
      name: "magnumripper/JohnTheRipper"
      description: "http://openwall.com/john"
    notification_email: john.magnum@hushmail.com
    build_command_prepend:
    build_command: "cd src && ./configure && make -sj4 && echo -e '[Disabled:Formats]\nRaw-SHA512-free-opencl = Y\nXSHA512-free-opencl = Y' > john-local.conf && ../run/john -test-full=0"
    branch_pattern: coverity_scan
