language: c
dist: trusty

env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "FJ1/E5vVttd4+cFLQVdFt4rHNX28aGIvAWXduy6ZqQgZbfa0omsHcZXAq0t1qFz14ryTxEtxqY/aXw6OSG+t6a8OyrOi9jEdTIUpEDCyPvdZ299injPt1SiJRxzoDNo1CquwUE20y2pFOnTpVp6bIkH49o0oAxBijtb5fDj54KY="

matrix:
  include:
  - compiler: clang
    env: ASAN="--enable-asan"

  - compiler: gcc
    env: ASAN="--enable-asan"

  - compiler: clang
    env: ASAN=""

  allow_failures:
  - compiler: clang
    env: ASAN="--enable-asan"

  fast_finish: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libssl-dev yasm libgmp-dev libpcap-dev pkg-config debhelper libnet1-dev
  - sudo apt-get install fglrx-dev opencl-headers || true
  - export OMP_NUM_THREADS=4
script:
  - cd src
  - export LOG=$(git log -n 1)
  - if [[ $LOG == *'[no asan]'* ]]; then export ASAN=""; fi
  - ./configure $ASAN
  - make -sj4
  - ../.travis/test.sh

addons:
  coverity_scan:
    project:
      name: "magnumripper/JohnTheRipper"
      description: "http://openwall.com/john"
    notification_email: john.magnum@hushmail.com
    build_command_prepend:
    build_command: "cd src && ./configure && make -sj4 && echo -e '[Disabled:Formats]\nRaw-SHA512-free-opencl = Y\nXSHA512-free-opencl = Y' > john-local.conf && ../run/john -test-full=0"
    branch_pattern: coverity_scan
